name: Pre-release Major

on:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-npm:
    name: Deploy on NPM
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'pre-release major:')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn

      - run: yarn publish-npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
